# Generated by Django 5.0 on 2023-12-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("category", models.CharField(default="", max_length=100)),
                ("sub_category", models.CharField(default="", max_length=100)),
                ("price", models.IntegerField(default=0)),
                ("des", models.CharField(max_length=300)),
                ("pub_date", models.DateField()),
                ("image", models.ImageField(default="", upload_to="shop/images/")),
            ],
        ),
    ]
