# Generated by Django 4.1 on 2024-01-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("riyasapp", "0002_rename_image_product_image1_remove_product_des_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sub_category",
            field=models.CharField(default="", max_length=500),
        ),
    ]
