# Generated by Django 4.1 on 2024-01-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("riyasapp", "0005_alter_customer_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="mobile",
            field=models.CharField(max_length=10),
        ),
    ]
