# Generated by Django 4.1 on 2024-01-22 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("riyasapp", "0007_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="qunatity",
            new_name="quantity",
        ),
    ]
