# Generated by Django 4.1 on 2024-01-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("riyasapp", "0008_rename_qunatity_cart_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
