# Generated by Django 4.1 on 2024-01-24 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("riyasapp", "0010_payment_orderplaced"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderplaced",
            name="customer",
        ),
    ]
