# Generated by Django 4.1 on 2024-01-24 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("riyasapp", "0011_remove_orderplaced_customer"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderPlaced",
        ),
    ]
