# Generated by Django 4.1 on 2024-02-01 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("riyasapp", "0013_orderplaced"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderplaced",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="razorpay_payment_id",
        ),
    ]
